development:
  app_id: '198269216852292'
  app_secret: 'c98edf1abd4280af8d9cb0a0fef7d2bf'
  app_scope: 'offline_access,user_photos,user_photo_video_tags,friends_photos,friends_photo_video_tags,publish_stream,email'

test:
  app_id: '123456'
  app_secret: 's3cr37'
  app_scope: 'offline_access,user_photos,user_photo_video_tags,friends_photos,friends_photo_video_tags,publish_stream,email'

staging:
  app_id: '175780329132792'
  app_secret: '3bc76328e880b94ffa258c8da0bb4a52'
  app_scope:  'offline_access,user_photos,user_photo_video_tags,friends_photos,friends_photo_video_tags,publish_stream,email'

production:
  app_id: ''
  app_secret: ''
  app_scope: ''
